art/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'art'
urlpatterns = [
    url(r'^$', views.art_home, name='art_home'),
    url(r'^works/(?P<slug>[-\w]+)/$', views.art_detail_page, name='art_detail_page'),
    url(r'^(?P<slug>[-\w]+)/$', views.art_by_category, name='art_by_category'),
]

blog/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.blog_home, name='blog_home'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', views.archive_by_month, name="blog_archive_by_month"),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', views.entry_detail, name="blog_entry_detail"),
    url(r'^tag/(?P<tag>[-\w]+)/$', views.tag_page, name="blog_tag_page"),
]

config/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()
from config import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^art/', include('art.urls', namespace='art')),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^$', 'art.views.art_home', name='art_home'),

    url(r'^', include('singlepage.urls', namespace='singlepage')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from markdown import markdown
from tagging.fields import TagField
from tagging.registry import register
import datetime, tagging

class Entry(models.Model):
    """
    Class defining blog post model
    """
    LIVE_STATUS = 1
    DRAFT_STATUS = 2
    HIDDEN_STATUS = 3
    STATUS_CHOICES = (
        (LIVE_STATUS, 'Live'),
        (DRAFT_STATUS, 'Draft'),
        (HIDDEN_STATUS, 'Hidden'),
        )
    title = models.CharField(max_length=250, help_text = u'Maximum 250 characters')
    excerpt = models.TextField(help_text = u'A short summary of the entry.')
    body = models.TextField()
    pub_date = models.DateTimeField(default=datetime.datetime.now)

    excerpt_html = models.TextField(editable=False, blank=True)
    body_html = models.TextField(editable=False, blank=True)

    enable_comments = models.BooleanField(default=True)
    slug = models.SlugField(unique_for_date='pub_date', help_text=u'Suggested value automatically generated from title. Must be unique.')
    status = models.IntegerField(choices=STATUS_CHOICES, default=LIVE_STATUS, help_text=u'Only entries with live status will be publicly displayed.')

    tags = TagField(help_text=u'Seperate tags with spaces.')

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = u'Entries'

    def __unicode__(self):
        return self.title

    def save(self, force_insert=False, force_update=False):
        self.body_html = markdown(self.body)
        self.excerpt_html = markdown(self.excerpt)
        super(Entry, self).save(force_insert, force_update)

    @models.permalink
    def get_absolute_url(self):
        return ('blog_entry_detail', (), { 'year': self.pub_date.strftime("%Y"),
                                           'month': self.pub_date.strftime("%b").lower(),
                                           'day': self.pub_date.strftime("%d"),
                                           'slug': self.slug })
    
register(Entry, tag_descriptor_attr='etags')

blog/views.py
from blog.models import Entry
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.db.models import F
import datetime, time

MONTH_NAMES = ('', 'January', 'Feburary', 'March', 'April', 'May', 'June', 'July',
               'August', 'September', 'October', 'November', 'December')

def blog_home(request):
    """
    Blog home will show all blog entries from latest to oldest
    """
    return render_to_response('blog/blog_home.html', {'entries': Entry.objects.filter(status = 1)}, context_instance=RequestContext(request))

def archive_by_month(request, year, month):
    """
    Displays all blog entries based on month and year
    """
    date_stamp = time.strptime(year+month, "%Y%m")
    pub_date = datetime.date(*date_stamp[:3])
    entries = Entry.objects.filter(status = 1).filter(Q(pub_date__year = pub_date.year)).filter(Q(pub_date__month = pub_date.month))
    ctx = {'entries':entries, 'year':year, 'month':MONTH_NAMES[int(month)]}
    return render_to_response('blog/archive_by_month.html', ctx, context_instance=RequestContext(request))

def entry_detail(request, year, month, day, slug):
    """
    Displays detailed blog entry page
    """
    date_stamp = time.strptime(year+month+day, "%Y%b%d")
    pub_date = datetime.date(*date_stamp[:3])
    entry = get_object_or_404(Entry, pub_date__year=pub_date.year,
                                pub_date__month=pub_date.month,
                                pub_date__day=pub_date.day,
                                slug=slug)
    return render_to_response('singlepage/blog_entry.html',	{'entry': entry }, context_instance=RequestContext(request))

def tag_page(request, tag):
    entries = Entry.objects.filter(status = 1).filter(tags__contains = tag)
    return render_to_response('blog/blog_home.html',{'entries': entries, 'tag': tag }, context_instance=RequestContext(request))

templates/blog/archive_by_month.html
{% extends 'blog/blog_base.html' %}

{% block main-content %}

	<h3> Blog Archive for {{ month|capfirst }} {{ year }} : </h3>
	<br/>

	{% for entry in entries %}

		<div id="all-entries">
			<h3><a href= {{ entry.get_absolute_url }}> {{entry.title}} </a></h3>
			<br/>
			{{entry.pub_date}} 
			<br/><br/>
			{{entry.excerpt}}
			<br/><br/>

			{% if entry.etags.count %}
	        	<p>Tags: 
	            {% for tag in entry.etags %}
	                <a href={% url 'blog:blog_tag_page' tag=tag.name %} class="label">{{ tag.name }}</a>
	            {% endfor %}
		        </p>
		    {% endif %}

		    <br/>
		        <ul class="nav nav-list">
			    <li class="divider"></li>
			    </ul>
		    <br/>
		</div>

	{% endfor %}

{% endblock %}

templates/blog/blog_base.html
{% extends 'base.html' %}

{% block content %}
	<div class="span2"></div>
	<div id="main-content" class="span6" style="padding-top:3%;"> 
		{% block main-content %} {% endblock %}
	</div>
        <div id="categories" class="span2" style="text-align:right; padding-top:2%;">
       		 <ul class="unstyled">
                 	<li class="categories-header">Categories</li>
                       	<li><a href={% url 'blog:blog_home' %}>All</a></li>
                        {% for tag in tag_list %}
                        	<li><a href={% url 'blog:blog_tag_page' tag=tag.name %} style="text-decoration: none;">{{tag.name|capfirst}}</a></li>
                       	{% endfor %}
             	 </ul>
	</div>
       	<div class="span2"></div>
{% endblock %}

templates/blog/blog_home.html
{% extends 'blog/blog_base.html' %}

{% block main-content %}

	{% for entry in entries %}

		<div id="all-entries">
			<div class="header"><a href= {% url 'blog:blog_entry_detail' slug=entry.slug year=entry.pub_date|date:"Y" month=entry.pub_date|date:"b" day=entry.pub_date|date:"d" %}>{{entry.title}}</a>
			<br/>
			<span class="date">{{entry.pub_date|date}} | </span>
			<span class="tags">in 
			{% if entry.etags.count %}
	                   <i> {% for tag in entry.etags %}
        	                <a href={% url 'blog:blog_tag_page' tag=tag.name %}>{{ tag.name|upper }}{% if not forloop.last %}, {% endif %}</a>
			    {% endfor %}</i>
                        {% endif %}
			</div>
			<p/>		
			<div class="body">{{entry.excerpt|safe}}</div>
			
			<br/>	
			{% if not forloop.last %}
				<div class="underline"></div>
			{% endif %}
			<br/>

		</div>

	{% endfor %}

{% endblock %}