art/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'art'
urlpatterns = [
    url(r'^$', views.art_home, name='art_home'),
    url(r'^works/(?P<slug>[-\w]+)/$', views.art_detail_page, name='art_detail_page'),
    url(r'^(?P<slug>[-\w]+)/$', views.art_by_category, name='art_by_category'),
]

blog/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.blog_home, name='blog_home'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', views.archive_by_month, name="blog_archive_by_month"),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', views.entry_detail, name="blog_entry_detail"),
    url(r'^tag/(?P<tag>[-\w]+)/$', views.tag_page, name="blog_tag_page"),
]

config/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()
from config import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^art/', include('art.urls', namespace='art')),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^$', 'art.views.art_home', name='art_home'),

    url(r'^', include('singlepage.urls', namespace='singlepage')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

singlepage/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'singlepage'
urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', views.single_page, name='single_page'),
]

art/models.py
from django.db import models
from markdown import markdown
from tagging.fields import TagField
from tagging.registry import register
import datetime, tagging, os

class Art(models.Model):
    """
    Class defining art work model
    """

    def get_upload_path_high(instance, filename):
        return os.path.join(instance.art_type.category, "high", filename)

    def get_upload_path_low(instance, filename):
        return os.path.join(instance.art_type.category, "low", filename)

    title = models.CharField(max_length=250, help_text=u'Max 250 characters')
    slug = models.SlugField(unique=True, help_text=u'Suggested value automatically generated from title. Must be unique.')
    body = models.TextField()
    body_html = models.TextField(editable=False, blank=True)
    pub_date = models.DateTimeField(default=datetime.datetime.now)
    art_type = models.ForeignKey('Art_Category', on_delete=models.CASCADE)
    tags = TagField(help_text=u'Seperate tags with spaces.')
    url = models.URLField('URL', null=True, blank=True)
    image_highres = models.ImageField(upload_to=get_upload_path_high, null=True, blank=True)
    image_lowres = models.ImageField(upload_to=get_upload_path_low, null=True, blank=True)
    client_name = models.CharField(max_length=250, help_text=u'Max 250 characters', blank=True, null=True)
    order_num = models.IntegerField(default=0)

    class Meta:
        ordering = ['order_num']

    def __unicode__(self):
        return self.title

    def save(self, force_insert=False, force_update=False):
        self.body_html = markdown(self.body)
        super(Art, self).save(force_insert, force_update)

    def low_res_image_tag(self):
        return markdown('<img src="/%s/%s/%s" width="30%" height="30%" />' % (self.art_type, "low", self.image_lowres))

    def high_res_image_tag(self):
        return markdown('<img src="/%s/%s/%s" width="70%" height="70%" />' % (self.art_type, "high", self.image_highres))

    @models.permalink
    def get_absolute_url(self):
        return ('art_detail_page', (), { 'slug': self.slug })

register(Art, tag_descriptor_attr='atags')


class Art_Category(models.Model):
    """
    Class defining art types
    """
    category = models.CharField(max_length=100, help_text=u'Max 100 characters')
    slug = models.SlugField(unique=True, help_text=u'Suggested value automatically generated from title. Must be unique.')

    class Meta:
        verbose_name = "Art Category"
        verbose_name_plural = "Art Categories"
        ordering = ['category']

    def __unicode__(self):
        return self.category

    def __str__(self):
        return self.category

class Art_Url(models.Model):
    body = models.TextField(blank=True)
    body_html = models.TextField(editable=False, blank=True, null=True)
    url = models.URLField('URL', null=True, blank=True)
    art = models.ForeignKey('Art', on_delete=models.CASCADE)
    sequence = models.IntegerField()

    class Meta:
        ordering = ['sequence']

    def save(self, force_insert=False, force_update=False):
        self.body_html = markdown(self.body)
        super(Art_Url, self).save(force_insert, force_update)

singlepage/models.py
from django.db import models
from markdown import markdown

class Singlepage(models.Model):
    title = models.CharField(max_length=250, help_text=u'Max 250 characters')
    slug = models.SlugField(help_text=u'Suggested value automatically generated from title. Must be unique.')
    display_word = models.CharField(max_length=50, help_text=u'Max 50 characters. Displayed in the header.')
    body = models.TextField()
    body_html = models.TextField(editable=False, blank=True)
    url = models.URLField('URL', null=True, blank=True)

    def __unicode__(self):
        return self.title

    def save(self, force_insert=False, force_update=False):
        self.body_html = markdown(self.body)
        super(Singlepage, self).save(force_insert, force_update)

    @models.permalink
    def get_absolute_url(self):
        return ('single_page', (), { 'slug': self.slug })

singlepage/views.py
from django.shortcuts import render
from .models import Singlepage
from django.shortcuts import render, get_object_or_404, render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect

def single_page(request, slug):
    singlepage = get_object_or_404(Singlepage, slug=slug)
    return render_to_response('singlepage/single_page.html', {'singlepage': singlepage}, context_instance=RequestContext(request))

templates/singlepage/art_detail_page.html
{% extends 'singlepage/single_base.html' %}

{% block detaillist %}
    <li class="art_details_heading">Client</li>
    <li class="art_details_content">{% if art.client_name %} {{art.client_name}} {% else %} Personal Work {% endif %} </li>
    <li class="art_details_heading">Year</li>
    <li class="art_details_content">{{art.pub_date|date}} </li>	
    <li class="art_details_heading">Project Type</li>
    <li class="art_details_content">{{art.art_type.category}}</li>
{% endblock %}

{% block promotext %}
    <div class="anjana_profile_text">{{art.body|safe}}</div>
{% endblock %}

{% block main-content %}
    {% for image in art.art_url_set.all %}
    <div class="project_stuff">
        <img class="artdetail_image" srcset="{{image.url}}" alt="image{{image.sequence}}"/>
        {{image.body|safe}}
    </div>
    {% endfor %}
{% endblock %}

templates/singlepage/blog_entry.html
{% extends 'singlepage/single_base.html' %}

{% block main-content %}

        <div class="header"> {{entry.title}}
            <br/>
            <span class="date">{{entry.pub_date|date}} | </span>
            <span class="tags">in
                {% if entry.etags.count %}
                    <i> {% for tag in entry.etags %}
                        <a href={% url 'blog:blog_tag_page' tag=tag.name %}>{{ tag.name|upper }}{% if not forloop.last %}, {% endif %}</a>
                    {% endfor %}</i>
                {% endif %}
            </span>
        </div>
        <p/>
        <span class="body">{{entry.body|safe}}</span>

{% endblock %}

templates/singlepage/project_detail_page.html
{% extends 'singlepage/single_base.html' %}

{% block main-content %}

        <div class="header"> {{project.title}}
        </div>
        <span class="url"><a href="{{ project.url }}"> {{ project.url }} </a> </span>
        <p/>
        <span class="body">{{project.about|safe}}</span>

{% endblock %}

templates/singlepage/single_base.html
{% extends 'base.html' %}

{% block navigatorlist %}
<ul class="detailslist">
	{% block detaillist %}
	{% endblock %}
</ul>
{% endblock %}

{% block promotext %}
{% endblock %}

{% block content %}
	{% block main-content %} {% endblock %}
{% endblock %}

templates/singlepage/single_page.html
{% extends 'singlepage/single_base.html' %}

{% block main-content %}

<div class="row">
        <div class="columns medium-6">
                <div class="profile_pic">
                        <figure class="project_image">
				<picture class="project_image">
					{% if singlepage.url %} <img class="project_image" srcset="{{singlepage.url}}" alt="Anjana-Profile-Image" /> {% endif %}
				</picture>
			</figure>
                </div>
        </div>
        <div class="columns medium-6">
                <div class="content">
                        {{singlepage.body|safe}}
                </div>
        </div>
</div>

{% endblock %}