art/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'art'
urlpatterns = [
    url(r'^$', views.art_home, name='art_home'),
    url(r'^works/(?P<slug>[-\w]+)/$', views.art_detail_page, name='art_detail_page'),
    url(r'^(?P<slug>[-\w]+)/$', views.art_by_category, name='art_by_category'),
]

blog/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.blog_home, name='blog_home'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$', views.archive_by_month, name="blog_archive_by_month"),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$', views.entry_detail, name="blog_entry_detail"),
    url(r'^tag/(?P<tag>[-\w]+)/$', views.tag_page, name="blog_tag_page"),
]

config/urls.py
from django.conf.urls import url, include, patterns
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()
from config import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^art/', include('art.urls', namespace='art')),
    url(r'^project/', include('project.urls', namespace='project')),
    url(r'^$', 'art.views.art_home', name='art_home'),

    url(r'^', include('singlepage.urls', namespace='singlepage')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'project'
urlpatterns = [
    url(r'^$', views.project_home, name='project_home'),
    url(r'^(?P<slug>[-\w]+)/$', views.project_detail_page, name='project_detail_page'),
]

singlepage/urls.py
from django.conf.urls import url, include, patterns
from . import views

app_name = 'singlepage'
urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', views.single_page, name='single_page'),
]

templates/base.html
<html>
	<head>
        <script src="https://use.typekit.net/zfc5yqh.js"></script>
        <script>try{Typekit.load({ async: false });}catch(e){}</script>
		<meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Anjana</title>
		<link rel="stylesheet" href="/static/css/style.css" />
        <link rel='stylesheet' href='/static/css/nprogress.css'/>
        <link rel="icon" type="image/png" sizes="96x96" href="/static/images/favicon-96x96.png">
        <script src="/static/js/modernizr.custom.js"></script>
	</head>
  <body>

    <div class="container">
        <div class="cbp-af-header">
			<div class="cbp-af-inner">
				<header class="header">
                    <div class="row">
                        <div class="small-5 medium-6 large-6 columns">
                            <div class="anjana_name"><a href={% url 'art:art_home' %} class="link special">Anjana Padmakumar</a></div>
                        </div>
                        <div class="columns small-7 medium-6 header__nav large-6">
                            <nav class="nav_links">
                                <a class="nav_link" href={% url 'art:art_home' %}>WORK</a>
                                <!--<a class="nav_link" href={% url 'project:project_home' %}>PROJECTS</a>-->
                                <!--<a class="nav_link" href={% url 'blog:blog_home' %}>BLOG</a>-->
                                {% for page in singlepages %}
                                <a class="nav_link" href={% url 'singlepage:single_page' slug=page.slug %}>{{page.display_word}}</a>
                                {% endfor %}
                            </nav>
                        </div>
                    </div>
                </header>
			</div>
    	</div>
        <div class="scene scene_top clearfix">

            <div class="promo_area row">
                <div class="columns small-12 medium-6">
            {% block navigatorlist %}
							<li><a class="make_black">All Projects</a></li>
							<li><a>Art Direction</a></li>
							<li><a>Editorial</a></li>
							<li><a>Type Design</a></li>
							<li><a>Illustrations</a></li>
							<li><a>3d Design</a></li>
            {% endblock %}
                </div>
                <div class="columns small-0 medium-6">
            {% block promotext %}
                    <div class="promo_text_div">
                        	<h1 class="promo_text">Anjana is a Designer,<br/>
                                 Illustrator and Story-Teller.</h1>
                    </div>
            {% endblock %}
                </div>
            </div>
            
        </div>
        <div class="scene_artwork">
            <div class="artwork row" id="artwork">
                {% block content %} {% endblock %}
            </div>
        </div>

        <footer>
            <div class="footer row">
                {% block footertext %}
                <div class="columns medium-6">
                    <p class="copyright"> All work by Anjana Padmakumar
                </div>
                <div class="columns medium-6 copyright">
                    © 2017
                </div>
                {% endblock %}
            </div>
        </footer>
    </div>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/foundation.min.js"></script>
    <script type="text/javascript" src="/static/js/classie.js"></script>
    <script type="text/javascript" src="/static/js/cbpAnimatedHeader.min.js"></script>
    <script src='/static/js/nprogress.js'></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <script type="text/javascript">
        NProgress.start();
        var interval = setInterval(function() { NProgress.inc(); }, 1000); 
        var imgs = document.images,
                len = imgs.length,
                counter = 0;
        var count_images_loaded = 0;

        var imgLoad = imagesLoaded(imgs);

        imgLoad.on( 'progress', function( instance, image ) {
            var result = image.isLoaded ? 'loaded' : 'broken';
            if(result == 'loaded')
            {
                count_images_loaded += 1;
            }
            var progress_percentage = count_images_loaded/imgs.length;
            console.log( 'image is ' + result + ' for ' + image.img.srcset );
            console.log( 'Setting progress % to ' + progress_percentage)
            NProgress.set(progress_percentage);
        });

        imgLoad.on( 'always', function( instance ) {
            console.log('ALWAYS - all images have been loaded');
            clearInterval(interval);
            NProgress.done();
        });

        jQuery.noConflict()(function ($) {
            $(document).foundation();
        });
    </script>
  </body>
</html>